// GENERATED by scripts/build-gallery-images.mjs — do not edit by hand.
// Source: the live cdl1983.ca gallery (see scripts/gallery-manifest.json).

export type GalleryImage = { src: string; width: number; height: number };

export const galleryImages: Record<string, GalleryImage[]> = {
  "5-points": [
    {
      "src": "/projects/5-points/01.jpg",
      "width": 1180,
      "height": 665
    },
    {
      "src": "/projects/5-points/02.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/5-points/03.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/5-points/04.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/5-points/05.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/5-points/06.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/5-points/07.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/5-points/08.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/5-points/09.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/5-points/10.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/5-points/11.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/5-points/12.jpg",
      "width": 2000,
      "height": 1125
    }
  ],
  "alexandra-court-clubhouse": [
    {
      "src": "/projects/alexandra-court-clubhouse/01.jpg",
      "width": 800,
      "height": 604
    },
    {
      "src": "/projects/alexandra-court-clubhouse/02.jpg",
      "width": 480,
      "height": 640
    },
    {
      "src": "/projects/alexandra-court-clubhouse/03.jpg",
      "width": 480,
      "height": 640
    },
    {
      "src": "/projects/alexandra-court-clubhouse/04.jpg",
      "width": 480,
      "height": 640
    },
    {
      "src": "/projects/alexandra-court-clubhouse/05.jpg",
      "width": 480,
      "height": 640
    },
    {
      "src": "/projects/alexandra-court-clubhouse/06.jpg",
      "width": 480,
      "height": 640
    },
    {
      "src": "/projects/alexandra-court-clubhouse/07.jpg",
      "width": 640,
      "height": 480
    }
  ],
  "astoria": [
    {
      "src": "/projects/astoria/01.jpg",
      "width": 800,
      "height": 364
    },
    {
      "src": "/projects/astoria/02.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/astoria/03.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/astoria/04.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/astoria/05.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/astoria/06.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/astoria/07.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/astoria/08.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/astoria/09.jpg",
      "width": 1296,
      "height": 864
    }
  ],
  "athenry": [
    {
      "src": "/projects/athenry/01.jpg",
      "width": 642,
      "height": 428
    },
    {
      "src": "/projects/athenry/02.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/athenry/03.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/athenry/04.jpg",
      "width": 1296,
      "height": 864
    }
  ],
  "aucoin-residence": [
    {
      "src": "/projects/aucoin-residence/01.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/aucoin-residence/02.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/aucoin-residence/03.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/aucoin-residence/04.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/aucoin-residence/05.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/aucoin-residence/06.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/aucoin-residence/07.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/aucoin-residence/08.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/aucoin-residence/09.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/aucoin-residence/10.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/aucoin-residence/11.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/aucoin-residence/12.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/aucoin-residence/13.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/aucoin-residence/14.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/aucoin-residence/15.jpg",
      "width": 1296,
      "height": 864
    }
  ],
  "aviara": [
    {
      "src": "/projects/aviara/01.jpg",
      "width": 864,
      "height": 576
    },
    {
      "src": "/projects/aviara/02.jpg",
      "width": 292,
      "height": 432
    },
    {
      "src": "/projects/aviara/03.jpg",
      "width": 292,
      "height": 432
    },
    {
      "src": "/projects/aviara/04.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/aviara/05.jpg",
      "width": 768,
      "height": 1024
    },
    {
      "src": "/projects/aviara/06.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/aviara/07.jpg",
      "width": 768,
      "height": 1024
    },
    {
      "src": "/projects/aviara/08.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/aviara/09.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/aviara/10.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/aviara/11.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/aviara/12.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/aviara/13.jpg",
      "width": 768,
      "height": 1024
    },
    {
      "src": "/projects/aviara/14.jpg",
      "width": 1028,
      "height": 771
    }
  ],
  "carrera-1": [
    {
      "src": "/projects/carrera-1/01.jpg",
      "width": 800,
      "height": 600
    },
    {
      "src": "/projects/carrera-1/02.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/carrera-1/03.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/carrera-1/04.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/carrera-1/05.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/carrera-1/06.jpg",
      "width": 1296,
      "height": 864
    }
  ],
  "carrera-2": [
    {
      "src": "/projects/carrera-2/01.jpg",
      "width": 800,
      "height": 600
    },
    {
      "src": "/projects/carrera-2/02.jpg",
      "width": 1296,
      "height": 950
    },
    {
      "src": "/projects/carrera-2/03.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/carrera-2/04.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/carrera-2/05.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/carrera-2/06.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/carrera-2/07.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/carrera-2/08.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/carrera-2/09.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/carrera-2/10.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/carrera-2/11.jpg",
      "width": 2000,
      "height": 1333
    },
    {
      "src": "/projects/carrera-2/12.jpg",
      "width": 1296,
      "height": 864
    }
  ],
  "charland": [
    {
      "src": "/projects/charland/01.jpg",
      "width": 480,
      "height": 480
    },
    {
      "src": "/projects/charland/02.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/charland/03.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/charland/04.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/charland/05.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/charland/06.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/charland/07.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/charland/08.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/charland/09.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/charland/10.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/charland/11.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/charland/12.jpg",
      "width": 1296,
      "height": 864
    }
  ],
  "dominion": [
    {
      "src": "/projects/dominion/01.jpg",
      "width": 1157,
      "height": 643
    },
    {
      "src": "/projects/dominion/02.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/dominion/03.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/dominion/04.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/dominion/05.jpg",
      "width": 1296,
      "height": 864
    }
  ],
  "edgemont": [
    {
      "src": "/projects/edgemont/01.jpg",
      "width": 1280,
      "height": 957
    },
    {
      "src": "/projects/edgemont/02.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/edgemont/03.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/edgemont/04.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/edgemont/05.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/edgemont/06.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/edgemont/07.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/edgemont/08.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/edgemont/09.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/edgemont/10.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/edgemont/11.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/edgemont/12.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/edgemont/13.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/edgemont/14.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/edgemont/15.jpg",
      "width": 768,
      "height": 1024
    },
    {
      "src": "/projects/edgemont/16.jpg",
      "width": 768,
      "height": 1024
    },
    {
      "src": "/projects/edgemont/17.jpg",
      "width": 768,
      "height": 1024
    },
    {
      "src": "/projects/edgemont/18.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/edgemont/19.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/edgemont/20.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/edgemont/21.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/edgemont/22.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/edgemont/23.jpg",
      "width": 2000,
      "height": 327
    },
    {
      "src": "/projects/edgemont/24.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/edgemont/25.jpg",
      "width": 768,
      "height": 1024
    },
    {
      "src": "/projects/edgemont/26.jpg",
      "width": 768,
      "height": 1024
    },
    {
      "src": "/projects/edgemont/27.jpg",
      "width": 768,
      "height": 1024
    },
    {
      "src": "/projects/edgemont/28.jpg",
      "width": 1024,
      "height": 768
    }
  ],
  "elmstone": [
    {
      "src": "/projects/elmstone/01.jpg",
      "width": 767,
      "height": 464
    },
    {
      "src": "/projects/elmstone/02.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/elmstone/03.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/elmstone/04.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/elmstone/05.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/elmstone/06.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/elmstone/07.jpg",
      "width": 2000,
      "height": 1125
    }
  ],
  "gardner": [
    {
      "src": "/projects/gardner/01.jpg",
      "width": 1280,
      "height": 853
    },
    {
      "src": "/projects/gardner/02.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/gardner/03.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/gardner/04.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/gardner/05.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/gardner/06.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/gardner/07.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/gardner/08.jpg",
      "width": 2000,
      "height": 1125
    }
  ],
  "hampton-cove": [
    {
      "src": "/projects/hampton-cove/01.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/hampton-cove/02.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/hampton-cove/03.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/hampton-cove/04.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/hampton-cove/05.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/hampton-cove/06.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/hampton-cove/07.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/hampton-cove/08.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/hampton-cove/09.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/hampton-cove/10.jpg",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/projects/hampton-cove/11.jpg",
      "width": 768,
      "height": 1024
    },
    {
      "src": "/projects/hampton-cove/12.jpg",
      "width": 768,
      "height": 1024
    },
    {
      "src": "/projects/hampton-cove/13.jpg",
      "width": 768,
      "height": 1024
    },
    {
      "src": "/projects/hampton-cove/14.jpg",
      "width": 768,
      "height": 1024
    },
    {
      "src": "/projects/hampton-cove/15.jpg",
      "width": 768,
      "height": 1024
    },
    {
      "src": "/projects/hampton-cove/16.jpg",
      "width": 768,
      "height": 1024
    },
    {
      "src": "/projects/hampton-cove/17.jpg",
      "width": 768,
      "height": 1024
    },
    {
      "src": "/projects/hampton-cove/18.jpg",
      "width": 768,
      "height": 1024
    }
  ],
  "kensington": [
    {
      "src": "/projects/kensington/01.jpg",
      "width": 440,
      "height": 324
    },
    {
      "src": "/projects/kensington/02.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/kensington/03.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/kensington/04.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/kensington/05.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/kensington/06.jpg",
      "width": 1296,
      "height": 864
    }
  ],
  "kingston": [
    {
      "src": "/projects/kingston/01.jpg",
      "width": 800,
      "height": 640
    },
    {
      "src": "/projects/kingston/02.jpg",
      "width": 1296,
      "height": 968
    },
    {
      "src": "/projects/kingston/03.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/kingston/04.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/kingston/05.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/kingston/06.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/kingston/07.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/kingston/08.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/kingston/09.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/kingston/10.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/kingston/11.jpg",
      "width": 1296,
      "height": 864
    }
  ],
  "kiwanis": [
    {
      "src": "/projects/kiwanis/01.jpg",
      "width": 609,
      "height": 457
    },
    {
      "src": "/projects/kiwanis/02.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/kiwanis/03.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/kiwanis/04.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/kiwanis/05.jpg",
      "width": 1296,
      "height": 864
    }
  ],
  "park-and-metro": [
    {
      "src": "/projects/park-and-metro/01.jpg",
      "width": 1802,
      "height": 600
    },
    {
      "src": "/projects/park-and-metro/02.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/park-and-metro/03.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/park-and-metro/04.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/park-and-metro/05.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/park-and-metro/06.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/park-and-metro/07.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/park-and-metro/08.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/park-and-metro/09.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/park-and-metro/10.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/park-and-metro/11.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/park-and-metro/12.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/park-and-metro/13.jpg",
      "width": 576,
      "height": 1024
    },
    {
      "src": "/projects/park-and-metro/14.jpg",
      "width": 576,
      "height": 1024
    },
    {
      "src": "/projects/park-and-metro/15.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/park-and-metro/16.jpg",
      "width": 576,
      "height": 1024
    },
    {
      "src": "/projects/park-and-metro/17.jpg",
      "width": 576,
      "height": 1024
    }
  ],
  "saltaire": [
    {
      "src": "/projects/saltaire/01.jpg",
      "width": 899,
      "height": 606
    },
    {
      "src": "/projects/saltaire/02.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/saltaire/03.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/saltaire/04.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/saltaire/05.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/saltaire/06.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/saltaire/07.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/saltaire/08.jpg",
      "width": 1296,
      "height": 864
    }
  ],
  "stanton-house": [
    {
      "src": "/projects/stanton-house/01.jpg",
      "width": 750,
      "height": 403
    },
    {
      "src": "/projects/stanton-house/02.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/stanton-house/03.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/stanton-house/04.jpg",
      "width": 576,
      "height": 1024
    },
    {
      "src": "/projects/stanton-house/05.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/stanton-house/06.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/stanton-house/07.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/stanton-house/08.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/stanton-house/09.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/stanton-house/10.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/stanton-house/11.jpg",
      "width": 1024,
      "height": 576
    },
    {
      "src": "/projects/stanton-house/12.jpg",
      "width": 1024,
      "height": 576
    }
  ],
  "storybrook": [
    {
      "src": "/projects/storybrook/01.jpg",
      "width": 944,
      "height": 412
    },
    {
      "src": "/projects/storybrook/02.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/storybrook/03.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/storybrook/04.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/storybrook/05.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/storybrook/06.jpg",
      "width": 1296,
      "height": 864
    }
  ],
  "trafalgar": [
    {
      "src": "/projects/trafalgar/01.jpg",
      "width": 767,
      "height": 464
    },
    {
      "src": "/projects/trafalgar/02.jpg",
      "width": 1125,
      "height": 2000
    },
    {
      "src": "/projects/trafalgar/03.jpg",
      "width": 1125,
      "height": 2000
    },
    {
      "src": "/projects/trafalgar/04.jpg",
      "width": 1125,
      "height": 2000
    },
    {
      "src": "/projects/trafalgar/05.jpg",
      "width": 1125,
      "height": 2000
    },
    {
      "src": "/projects/trafalgar/06.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/trafalgar/07.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/trafalgar/08.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/trafalgar/09.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/trafalgar/10.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/trafalgar/11.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/trafalgar/12.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/trafalgar/13.jpg",
      "width": 2000,
      "height": 1125
    }
  ],
  "union-park": [
    {
      "src": "/projects/union-park/01.jpg",
      "width": 767,
      "height": 464
    },
    {
      "src": "/projects/union-park/02.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/03.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/04.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/05.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/06.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/07.jpg",
      "width": 1125,
      "height": 2000
    },
    {
      "src": "/projects/union-park/08.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/09.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/10.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/11.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/12.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/13.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/14.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/15.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/16.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/17.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/18.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/19.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/20.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/21.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/22.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/23.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/24.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/25.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/26.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/27.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/28.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/29.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/30.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/31.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/32.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/33.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/34.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/35.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/36.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/union-park/37.jpg",
      "width": 2000,
      "height": 1125
    }
  ],
  "vittorio": [
    {
      "src": "/projects/vittorio/01.jpg",
      "width": 767,
      "height": 464
    },
    {
      "src": "/projects/vittorio/02.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/vittorio/03.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/vittorio/04.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/vittorio/05.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/vittorio/06.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/vittorio/07.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/vittorio/08.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/vittorio/09.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/vittorio/10.jpg",
      "width": 2000,
      "height": 1125
    },
    {
      "src": "/projects/vittorio/11.jpg",
      "width": 2000,
      "height": 1125
    }
  ],
  "woodcroft": [
    {
      "src": "/projects/woodcroft/01.jpg",
      "width": 1500,
      "height": 1001
    },
    {
      "src": "/projects/woodcroft/02.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/woodcroft/03.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/woodcroft/04.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/woodcroft/05.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/woodcroft/06.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/woodcroft/07.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/woodcroft/08.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/woodcroft/09.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/woodcroft/10.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/woodcroft/11.jpg",
      "width": 1296,
      "height": 864
    },
    {
      "src": "/projects/woodcroft/12.jpg",
      "width": 1296,
      "height": 864
    }
  ]
};

export const galleryCovers: Record<string, GalleryImage | undefined> =
  Object.fromEntries(
    Object.entries(galleryImages).map(([slug, images]) => [slug, images[0]]),
  );
